apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}-resource-injector
webhooks:
  - name: resource.injector.k8s.io
    clientConfig:
      service:
        name: {{ .Release.Name }}-resource-injector
        namespace: {{ .Values.namespace }}
        path: /mutate
      caBundle: {{ .Values.webhook.caBundle }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE"]